# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
